### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by Wekendd** [Wekendd/housatic-cli#1]
- [x] **0.1.0**
  - [x] Open beta 🎉
- [x] **0.2.0**
  - [x] Complete console view functionality
  - [x] Complete bot rename functionality
  - [x] Make things look better
- [ ] **0.3.0**
  - [ ] Add custom language for enhanced bot scripting
  - [x] Add ability to run commands from console
  - [x] Add bot configuring after creation
  - [ ] Improve documentation
